# PHREEQC PROJECT CODES

These notebook's function is to aide in comparing each REE's elemental values, comparing different k values in REE speciations, checking which Ree speciations are included in the database and which else should be included.

Imports

In [1]:
import re
import pandas as pd
from pqcdbchk.build_database import clean_tables as ct
from pqcdbchk.build_database import utils as ut
import importlib.resources as pkg_resources

Setup

In [2]:
# Enter the directory of your databases in the parenthesis below:
database_list = pkg_resources.files("pqcdbchk.build_database.databases")
database_list = ut.phreeqc_database_list(database_list)

# create Solution Species table
solution_species = ct.compile_solution_species_table(database_list)

# create Solution Master Species table
sms = ct.compile_master_solution_table(database_list, analysis=True)

# create Phases table
phases = ct.compile_phase_table(database_list)

# drop duplicate rows
before = len(sms)
filter_columns = ["element"]
sms = sms.drop_duplicates(subset=filter_columns)
after = len(sms)
print(f"Filtered {before - after} duplicate rows from Solution Master Species table")

filter_columns = ["equation"]
before = len(solution_species)
filter_columns = solution_species.columns[:-1]
solution_species = solution_species.drop_duplicates(subset=filter_columns)
after = len(solution_species)
print(f"Filtered {before - after} duplicate rows from Solution Species table")

filter_columns = ["phase_name"]
before = len(phases)
filter_columns = phases.columns[:-1]
phases = phases.drop_duplicates(subset=filter_columns)
after = len(phases)
print(f"Filtered {before - after} duplicate rows from Phases table")

Filtered 399 duplicate rows from Solution Master Species table
Filtered 347 duplicate rows from Solution Species table
Filtered 0 duplicate rows from Phases table

In [3]:
# Here is a list of all your database combined:
display(sms)
display(solution_species)
display(phases)

# If you want them exported into an excel file, simply activate the code below - and write your intended file name in the brackets:
with pd.ExcelWriter("database_lists.xlsx") as writer:
    sms.to_excel(writer, sheet_name="sms", index=False)
    solution_species.to_excel(writer, sheet_name="solution_species", index=False)
    phases.to_excel(writer, sheet_name="phases", index=False)

        element     species  alk    gfw_formula element_gfw       source
0    Alkalinity       CO3-2  1.0  Ca0.5(CO3)0.5       50.05  #pitzer.dat
1             B      B(OH)3  0.0              B       10.81  #pitzer.dat
2            Ba        Ba+2  0.0             Ba      137.33  #pitzer.dat
3            Br         Br-  0.0             Br      79.904  #pitzer.dat
4             C       CO3-2  2.0           HCO3     12.0111  #pitzer.dat
..          ...         ...  ...            ...         ...          ...
85     Phthalat  Phthalat-2  0.0       Phthalat     164.084     #sit.dat
91     Pyrophos  Pyrophos-4  0.0       Pyrophos      173.95     #sit.dat
103         Scn        Scn-  0.0            Scn      58.084     #sit.dat
114    Suberate  Suberate-2  0.0       Suberate      170.16     #sit.dat
115    Succinat  Succinat-2  0.0       Succinat      116.07     #sit.dat

[285 rows x 6 columns]

,equation,log_k,delta_h,gamma,d_w,v_m,millero,activity_water,add_logk,llnl_gamma,co2_llnl_gamma,erm_ddl,no_check,mole_balance,source
0,H+ = H+,0.00,None,None,"(9.31e-09, 1000.0, 0.46, 1e-10)",None,None,None,None,NaN,None,None,False,None,pitzer.dat
1,e- = e-,0.00,None,None,None,None,None,None,None,NaN,None,None,False,None,pitzer.dat
2,H2O = H2O,0.00,None,None,None,None,None,None,None,NaN,None,None,False,None,pitzer.dat
3,Li+ = Li+,0.00,None,None,"(1.03e-09, 80.0)","(-0.419, -0.069, 13.16, -2.78, 0.416, 0.0, 0.2...",None,None,None,NaN,None,None,False,None,pitzer.dat
4,Na+ = Na+,0.00,None,None,"(1.33e-09, 122.0, 1.52, 3.7)","(2.28, -4.38, -4.1, -0.586, 0.09, 4.0, 0.3, 52...",None,None,None,NaN,None,None,False,None,pitzer.dat
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4888,4F- + 1Zr+4 = ZrF4,30.11,"(-22.000,)",None,None,None,None,None,None,NaN,None,None,False,None,sit.dat
4889,5F- + 1Zr+4 = ZrF5-,34.60,None,None,None,None,None,None,None,NaN,None,None,False,None,sit.dat
4890,6F- + 1Zr+4 = ZrF6-2,38.11,None,None,None,None,None,None,None,NaN,None,None,False,None,sit.dat
4891,1NO3- + 1Zr+4 = ZrNO3+3,1.59,None,None,None,None,None,None,None,NaN,None,None,False,None,sit.dat
4892,1SO4-2 + 1Zr+4 = ZrSO4+2,7.04,"(36.940,)",None,None,None,None,None,None,NaN,None,None,False,None,sit.dat

,phase_name,dissolution_reaction,log_k,delta_h,analytic,v_m,t_c,p_c,omega,source
0,Akermanite,Ca2MgSi2O7 + 6 H+ = Mg+2 + 2 Ca+2 + 2 H4SiO4 -...,45.23,"(-289, kJ/mol)",None,"(92.6,)",None,None,None,pitzer.dat
1,Anhydrite,CaSO4 = Ca+2 + SO4-2,-4.362,None,"(5.009, -2.21e-2, -796.4)","(46.1,)",None,None,None,pitzer.dat
2,Anthophyllite,Mg7Si8O22(OH)2 + 14 H+ = 7 Mg+2 - 8 H2O + 8 H4...,66.8,"(-483, kJ/mol)",None,"(269.0,)",None,None,None,pitzer.dat
3,Antigorite,Mg48Si34O85(OH)62 + 96 H+ = 34 H4SiO4 + 48 Mg+...,477.19,"(-3364, kJ/mol)",None,"(1745.0,)",None,None,None,pitzer.dat
4,Aragonite,CaCO3 = CO3-2 + Ca+2,-8.336,"(-2.589, kcal)","(-171.8607, -.077993, 2903.293, 71.595)","(34.04,)",None,None,None,pitzer.dat
...,...,...,...,...,...,...,...,...,...,...
2741,H2O(g),H2O = 1H2O,1.5,"(-44.004,)","(-6.20916E+0, 0E+0, 2.29849E+3, 0E+0, 0E+0)",None,None,None,None,sit.dat
2742,H2S(g),H2S = 1H+ + 1HS-,-8.0,"(4.300,)","(-7.24667E+0, 0E+0, -2.24604E+2, 0E+0, 0E+0)",None,None,None,None,sit.dat
2743,HCl(g),HCl = 1H+ + 1Cl-,6.29,"(-74.770,)","(-6.80912E+0, 0E+0, 3.9055E+3, 0E+0, 0E+0)",None,None,None,None,sit.dat
2744,O2(g),O2 = 1O2,-2.9,"(-12.134,)","(-5.02578E+0, 0E+0, 6.33802E+2, 0E+0, 0E+0)",None,None,None,None,sit.dat
2745,SO2(g),SO2 = 2H+ + 1SO3-2 - 1H2O,-8.94,"(-48.420,)","(-1.74228E+1, 0E+0, 2.52915E+3, 0E+0, 0E+0)",None,None,None,None,sit.dat

In [4]:
# functions for searching desired values - use whichever you like to see the database values of certain equation/species/phases

# this is for the solution_master_speices block
def find_species(species: str):
    find_sp = sms[sms["species"].str.contains(species, regex=False)]
    return find_sp


# this is for the solution species
def find_equation(equation: str):
    equation = equation.replace(" ", "")
    equation = re.sub(r"\b1(?!\d)", "", equation)
    find_eq = solution_species[
        solution_species["equation"].str.contains(equation, regex=False)
    ]
    return find_eq


# this is for the phases block
def find_phases(species: str):
    find_phases = phases[phases["phase_name"].str.contains(species, regex=False)]
    return find_phases


# here are the example template. Type in the equation/find_species/find_phases in the brackets of each function:
display(find_species("La"))
display(find_equation("YbF"))
display(find_phases("Quartz"))

# If you want to export these, you can use codes below after altering it for your desired function/search value:
find_species("La").to_excel("La_species.xlsx", index=False)

    element species  alk gfw_formula element_gfw     source
104      La    La+3  0.0          La    138.9055  #llnl.dat
105  La(+2)    La+2  0.0          La         NaN  #llnl.dat
106  La(+3)    La+3  0.0          La         NaN  #llnl.dat

,equation,log_k,delta_h,gamma,d_w,v_m,millero,activity_water,add_logk,llnl_gamma,co2_llnl_gamma,erm_ddl,no_check,mole_balance,source
3402,Yb+3 + F- = YbF+2,4.8085,"(23.2212, kJ/mol)",None,None,None,None,None,None,4.5,None,None,False,None,llnl.dat
3403,2F- + Yb+3 = YbF2+,8.3709,"(12.1336, kJ/mol)",None,None,None,None,None,None,4.0,None,None,False,None,llnl.dat
3404,3F- + Yb+3 = YbF3,11.0537,"(-13.1796, kJ/mol)",None,None,None,None,None,None,3.0,None,None,False,None,llnl.dat
3405,4F- + Yb+3 = YbF4-,13.2234,"(-60.2496, kJ/mol)",None,None,None,None,None,None,4.0,None,None,False,None,llnl.dat

,phase_name,dissolution_reaction,log_k,delta_h,analytic,v_m,t_c,p_c,omega,source
48,Quartz,SiO2 + 2 H2O = H4SiO4,-3.98,"(5.990, kcal)",None,"(22.67,)",None,None,None,pitzer.dat
220,Quartz,SiO2 + 2H2O = H4SiO4,-4.0,"(22.36, kJ)",None,None,None,None,None,minteq.v4.dat
1394,Quartz,SiO2 = + SiO2,-3.9993,"(32.949, kJ/mol)","(7.7698e-002, 1.0612e-002, 3.4651e+003, -4.355...",None,None,None,None,llnl.dat
2532,Quartz,SiO2 = 1H4(SiO4) - 2H2O,-3.74,"(21.166,)","(-3.18814E-2, 0E+0, -1.10558E+3, 0E+0, 0E+0)",None,None,None,None,sit.dat